"""Public-API compatibility test.

Guards the surface recorded in ``upstream_exports.json``, generated by
``tools/gen_export_inventory.py`` from the fork point: every module still
imports, every public name a module defined still resolves, every incidental
alias marked ``keep`` still resolves to the same object it aliased, and the
package still re-exports what it did.

Nothing is constructed here on purpose: the test imports and reads attributes
only, so it checks the import surface and nothing else (paho 2.x, for one,
warns about the callback API version whenever a client is built).
"""

from __future__ import annotations

import importlib
import inspect
import json
from pathlib import Path

import pytest

INVENTORY = json.loads(
    Path(__file__).with_name("upstream_exports.json").read_text(encoding="utf-8")
)
PACKAGE = INVENTORY["package"]
MODULES = sorted(INVENTORY["modules"])

PUBLIC_NAMES = [
    pytest.param(module, name, kind, id=f"{module}.{name}")
    for module in MODULES
    for name, kind in INVENTORY["modules"][module]["defines"].items()
]
KEPT_ALIASES = [
    pytest.param(module, name, alias["source"], id=f"{module}.{name}")
    for module in MODULES
    for name, alias in INVENTORY["modules"][module]["aliases"].items()
    if alias["policy"] == "keep"
]
PACKAGE_IMPORTS = [
    pytest.param(name, source, id=name)
    for name, source in sorted(INVENTORY["package_imports"].items())
]


@pytest.mark.parametrize("module", MODULES)
def test_module_imports(module: str) -> None:
    importlib.import_module(module)


@pytest.mark.parametrize(("module", "name", "kind"), PUBLIC_NAMES)
def test_public_name_resolves(module: str, name: str, kind: str) -> None:
    obj = getattr(importlib.import_module(module), name)
    if kind == "class":
        assert inspect.isclass(obj), f"{module}.{name} is no longer a class"
    elif kind == "function":
        assert callable(obj), f"{module}.{name} is no longer callable"


@pytest.mark.parametrize(("module", "name", "source"), KEPT_ALIASES)
def test_kept_alias_resolves(module: str, name: str, source: str) -> None:
    aliased = getattr(importlib.import_module(module), name)
    original = getattr(importlib.import_module(source), name)
    assert aliased is original, f"{module}.{name} no longer aliases {source}.{name}"


@pytest.mark.parametrize(("name", "source"), PACKAGE_IMPORTS)
def test_package_reexports(name: str, source: str) -> None:
    exported = getattr(importlib.import_module(PACKAGE), name)
    original = getattr(importlib.import_module(source), name)
    assert exported is original, f"{PACKAGE}.{name} no longer re-exports {source}.{name}"


def test_all_names_arrive_with_star_import() -> None:
    namespace: dict[str, object] = {}
    exec(f"from {PACKAGE} import *", namespace)  # the star import is the point of this test
    missing = [name for name in INVENTORY["all"] if name not in namespace]
    assert not missing, f"names dropped from {PACKAGE}.__all__: {missing}"
    declared = importlib.import_module(PACKAGE).__all__
    assert set(INVENTORY["all"]) <= set(declared)


def test_mower_auth_error_importable_from_package() -> None:
    from mower_sdk import MowerAuthError
    from mower_sdk.errors import MowerAuthError as original

    assert MowerAuthError is original
